package com.myspace.poc_bc_cep;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@org.kie.api.definition.type.Expires("1m")
public class PqrCEPDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String numeroIdentificacion;
	private java.lang.String tipoIdentificacion;

	public PqrCEPDO() {
	}

	public java.lang.String getNumeroIdentificacion() {
		return this.numeroIdentificacion;
	}

	public void setNumeroIdentificacion(java.lang.String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	public java.lang.String getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(java.lang.String tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public PqrCEPDO(java.lang.String numeroIdentificacion,
			java.lang.String tipoIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
		this.tipoIdentificacion = tipoIdentificacion;
	}

}