package com.myspace.poc_bc_cep;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Expires("1m")
public class PQRFrecuente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String numeroIdentificacion;
	private java.lang.String tipoIdentificacion;
	private java.lang.Integer contador;

	public PQRFrecuente() {
	}

	public java.lang.String getNumeroIdentificacion() {
		return this.numeroIdentificacion;
	}

	public void setNumeroIdentificacion(java.lang.String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	public java.lang.String getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(java.lang.String tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public java.lang.Integer getContador() {
		return this.contador;
	}

	public void setContador(java.lang.Integer contador) {
		this.contador = contador;
	}

	public PQRFrecuente(java.lang.String numeroIdentificacion,
			java.lang.String tipoIdentificacion, java.lang.Integer contador) {
		this.numeroIdentificacion = numeroIdentificacion;
		this.tipoIdentificacion = tipoIdentificacion;
		this.contador = contador;
	}

}